/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReminderDTO model module.
 * @module model/ReminderDTO
 * @version 0.0.2
 */
class ReminderDTO {
    /**
     * Constructs a new <code>ReminderDTO</code>.
     * @alias module:model/ReminderDTO
     * @param medicineBarcode {String} medicineBarcode
     */
    constructor(medicineBarcode) { 
        
        ReminderDTO.initialize(this, medicineBarcode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, medicineBarcode) { 
        obj['medicineBarcode'] = medicineBarcode;
    }

    /**
     * Constructs a <code>ReminderDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReminderDTO} obj Optional instance to populate.
     * @return {module:model/ReminderDTO} The populated <code>ReminderDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReminderDTO();

            if (data.hasOwnProperty('medicineBarcode')) {
                obj['medicineBarcode'] = ApiClient.convertToType(data['medicineBarcode'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReminderDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReminderDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReminderDTO.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['medicineBarcode'] && !(typeof data['medicineBarcode'] === 'string' || data['medicineBarcode'] instanceof String)) {
            throw new Error("Expected the field `medicineBarcode` to be a primitive type in the JSON string but got " + data['medicineBarcode']);
        }

        return true;
    }


}

ReminderDTO.RequiredProperties = ["medicineBarcode"];

/**
 * medicineBarcode
 * @member {String} medicineBarcode
 */
ReminderDTO.prototype['medicineBarcode'] = undefined;






export default ReminderDTO;

