/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: v1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import UserCreateDTO from '../model/UserCreateDTO';
import UserDetailDTO from '../model/UserDetailDTO';
import UserLoginDTO from '../model/UserLoginDTO';
import UserTokenDTO from '../model/UserTokenDTO';

/**
* Authorization service.
* @module api/AuthorizationApi
* @version v1
*/
export default class AuthorizationApi {

    /**
    * Constructs a new AuthorizationApi. 
    * @alias module:api/AuthorizationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Login
     * @param {module:model/UserLoginDTO} userLoginDTO User credentials. username field must be users email
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserTokenDTO} and HTTP response
     */
    authControllerLoginWithHttpInfo(userLoginDTO) {
      let postBody = userLoginDTO;
      // verify the required parameter 'userLoginDTO' is set
      if (userLoginDTO === undefined || userLoginDTO === null) {
        throw new Error("Missing the required parameter 'userLoginDTO' when calling authControllerLogin");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserTokenDTO;
      return this.apiClient.callApi(
        '/auth/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Login
     * @param {module:model/UserLoginDTO} userLoginDTO User credentials. username field must be users email
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserTokenDTO}
     */
    authControllerLogin(userLoginDTO) {
      return this.authControllerLoginWithHttpInfo(userLoginDTO)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Logged User Detail
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserDetailDTO} and HTTP response
     */
    authControllerUserDetailWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserDetailDTO;
      return this.apiClient.callApi(
        '/auth/me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Logged User Detail
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserDetailDTO}
     */
    authControllerUserDetail() {
      return this.authControllerUserDetailWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Register user
     * @param {module:model/UserCreateDTO} userCreateDTO 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserTokenDTO} and HTTP response
     */
    authControllerUserRegisterWithHttpInfo(userCreateDTO) {
      let postBody = userCreateDTO;
      // verify the required parameter 'userCreateDTO' is set
      if (userCreateDTO === undefined || userCreateDTO === null) {
        throw new Error("Missing the required parameter 'userCreateDTO' when calling authControllerUserRegister");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserTokenDTO;
      return this.apiClient.callApi(
        '/auth/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Register user
     * @param {module:model/UserCreateDTO} userCreateDTO 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserTokenDTO}
     */
    authControllerUserRegister(userCreateDTO) {
      return this.authControllerUserRegisterWithHttpInfo(userCreateDTO)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
