/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: v1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CabinetDTO from '../model/CabinetDTO';

/**
* MedicineCabinet service.
* @module api/MedicineCabinetApi
* @version v1
*/
export default class MedicineCabinetApi {

    /**
    * Constructs a new MedicineCabinetApi. 
    * @alias module:api/MedicineCabinetApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the cabinetControllerCreate operation.
     * @callback module:api/MedicineCabinetApi~cabinetControllerCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CabinetDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add
     * @param {module:model/CabinetDTO} cabinetDTO 
     * @param {module:api/MedicineCabinetApi~cabinetControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CabinetDTO}
     */
    cabinetControllerCreate(cabinetDTO, callback) {
      let postBody = cabinetDTO;
      // verify the required parameter 'cabinetDTO' is set
      if (cabinetDTO === undefined || cabinetDTO === null) {
        throw new Error("Missing the required parameter 'cabinetDTO' when calling cabinetControllerCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CabinetDTO;
      return this.apiClient.callApi(
        '/cabinet', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the cabinetControllerDelete operation.
     * @callback module:api/MedicineCabinetApi~cabinetControllerDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete
     * @param {Number} id 
     * @param {module:api/MedicineCabinetApi~cabinetControllerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    cabinetControllerDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling cabinetControllerDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/cabinet/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the cabinetControllerFindUserAllItems operation.
     * @callback module:api/MedicineCabinetApi~cabinetControllerFindUserAllItemsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find User All Items
     * @param {module:api/MedicineCabinetApi~cabinetControllerFindUserAllItemsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    cabinetControllerFindUserAllItems(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/cabinet/findUserAllItems', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the cabinetControllerFindUserItem operation.
     * @callback module:api/MedicineCabinetApi~cabinetControllerFindUserItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find User Item
     * @param {Number} id 
     * @param {module:api/MedicineCabinetApi~cabinetControllerFindUserItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    cabinetControllerFindUserItem(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling cabinetControllerFindUserItem");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/cabinet/findUserItem/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the cabinetControllerUpdate operation.
     * @callback module:api/MedicineCabinetApi~cabinetControllerUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CabinetDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update
     * @param {Number} id 
     * @param {module:model/CabinetDTO} cabinetDTO 
     * @param {module:api/MedicineCabinetApi~cabinetControllerUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CabinetDTO}
     */
    cabinetControllerUpdate(id, cabinetDTO, callback) {
      let postBody = cabinetDTO;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling cabinetControllerUpdate");
      }
      // verify the required parameter 'cabinetDTO' is set
      if (cabinetDTO === undefined || cabinetDTO === null) {
        throw new Error("Missing the required parameter 'cabinetDTO' when calling cabinetControllerUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CabinetDTO;
      return this.apiClient.callApi(
        '/cabinet/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
