/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 08.10.2023
 *
 * The version of the OpenAPI document: v4.0.7
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RecipeDTO from '../model/RecipeDTO';

/**
* MedicineRecipe service.
* @module api/MedicineRecipeApi
* @version v4.0.7
*/
export default class MedicineRecipeApi {

    /**
    * Constructs a new MedicineRecipeApi. 
    * @alias module:api/MedicineRecipeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Find User Recipes
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RecipeDTO} and HTTP response
     */
    recipeControllerFindUserMedicinesWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RecipeDTO;
      return this.apiClient.callApi(
        '/recipe', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Find User Recipes
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RecipeDTO}
     */
    recipeControllerFindUserMedicines() {
      return this.recipeControllerFindUserMedicinesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
