/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: v1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApprovalDTO from '../model/ApprovalDTO';

/**
* UserApprovals service.
* @module api/UserApprovalsApi
* @version v1
*/
export default class UserApprovalsApi {

    /**
    * Constructs a new UserApprovalsApi. 
    * @alias module:api/UserApprovalsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the approvalControllerCreate operation.
     * @callback module:api/UserApprovalsApi~approvalControllerCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApprovalDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add
     * @param {module:model/ApprovalDTO} approvalDTO 
     * @param {module:api/UserApprovalsApi~approvalControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApprovalDTO}
     */
    approvalControllerCreate(approvalDTO, callback) {
      let postBody = approvalDTO;
      // verify the required parameter 'approvalDTO' is set
      if (approvalDTO === undefined || approvalDTO === null) {
        throw new Error("Missing the required parameter 'approvalDTO' when calling approvalControllerCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ApprovalDTO;
      return this.apiClient.callApi(
        '/approval', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the approvalControllerDelete operation.
     * @callback module:api/UserApprovalsApi~approvalControllerDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * De
     * @param {Number} id 
     * @param {module:api/UserApprovalsApi~approvalControllerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    approvalControllerDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling approvalControllerDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/approval/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the approvalControllerFindUserAllItems operation.
     * @callback module:api/UserApprovalsApi~approvalControllerFindUserAllItemsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find User All Items
     * @param {module:api/UserApprovalsApi~approvalControllerFindUserAllItemsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    approvalControllerFindUserAllItems(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/approval/findUserAllItems', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the approvalControllerFindUserItem operation.
     * @callback module:api/UserApprovalsApi~approvalControllerFindUserItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find User Item
     * @param {Number} id 
     * @param {module:api/UserApprovalsApi~approvalControllerFindUserItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    approvalControllerFindUserItem(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling approvalControllerFindUserItem");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/approval/findUserItem/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the approvalControllerUpdate operation.
     * @callback module:api/UserApprovalsApi~approvalControllerUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApprovalDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update
     * @param {Number} id 
     * @param {module:model/ApprovalDTO} approvalDTO 
     * @param {module:api/UserApprovalsApi~approvalControllerUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApprovalDTO}
     */
    approvalControllerUpdate(id, approvalDTO, callback) {
      let postBody = approvalDTO;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling approvalControllerUpdate");
      }
      // verify the required parameter 'approvalDTO' is set
      if (approvalDTO === undefined || approvalDTO === null) {
        throw new Error("Missing the required parameter 'approvalDTO' when calling approvalControllerUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ApprovalDTO;
      return this.apiClient.callApi(
        '/approval/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
