/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: v1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMobileApi);
  }
}(this, function(expect, KolayAsistanMobileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMobileApi.ApprovalDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApprovalDTO', function() {
    it('should create an instance of ApprovalDTO', function() {
      // uncomment below and update the code to test ApprovalDTO
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be.a(KolayAsistanMobileApi.ApprovalDTO);
    });

    it('should have the property agreementId (base name: "agreementId")', function() {
      // uncomment below and update the code to test the property agreementId
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be();
    });

    it('should have the property ip (base name: "ip")', function() {
      // uncomment below and update the code to test the property ip
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be();
    });

    it('should have the property device (base name: "device")', function() {
      // uncomment below and update the code to test the property device
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be();
    });

    it('should have the property kvkk (base name: "kvkk")', function() {
      // uncomment below and update the code to test the property kvkk
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be();
    });

    it('should have the property sms (base name: "sms")', function() {
      // uncomment below and update the code to test the property sms
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be();
    });

    it('should have the property adv (base name: "adv")', function() {
      // uncomment below and update the code to test the property adv
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be();
    });

    it('should have the property approvedDate (base name: "approvedDate")', function() {
      // uncomment below and update the code to test the property approvedDate
      //var instance = new KolayAsistanMobileApi.ApprovalDTO();
      //expect(instance).to.be();
    });

  });

}));
