/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: v1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMobileApi);
  }
}(this, function(expect, KolayAsistanMobileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMobileApi.CabinetDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CabinetDTO', function() {
    it('should create an instance of CabinetDTO', function() {
      // uncomment below and update the code to test CabinetDTO
      //var instance = new KolayAsistanMobileApi.CabinetDTO();
      //expect(instance).to.be.a(KolayAsistanMobileApi.CabinetDTO);
    });

    it('should have the property medicineBarcode (base name: "medicineBarcode")', function() {
      // uncomment below and update the code to test the property medicineBarcode
      //var instance = new KolayAsistanMobileApi.CabinetDTO();
      //expect(instance).to.be();
    });

    it('should have the property packType (base name: "packType")', function() {
      // uncomment below and update the code to test the property packType
      //var instance = new KolayAsistanMobileApi.CabinetDTO();
      //expect(instance).to.be();
    });

    it('should have the property packCount (base name: "packCount")', function() {
      // uncomment below and update the code to test the property packCount
      //var instance = new KolayAsistanMobileApi.CabinetDTO();
      //expect(instance).to.be();
    });

    it('should have the property expireDate (base name: "expireDate")', function() {
      // uncomment below and update the code to test the property expireDate
      //var instance = new KolayAsistanMobileApi.CabinetDTO();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instance = new KolayAsistanMobileApi.CabinetDTO();
      //expect(instance).to.be();
    });

  });

}));
