/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 08.10.2023
 *
 * The version of the OpenAPI document: v4.0.0.7
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMobileApi);
  }
}(this, function(expect, KolayAsistanMobileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMobileApi.MedicineDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MedicineDTO', function() {
    it('should create an instance of MedicineDTO', function() {
      // uncomment below and update the code to test MedicineDTO
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be.a(KolayAsistanMobileApi.MedicineDTO);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property barcode (base name: "barcode")', function() {
      // uncomment below and update the code to test the property barcode
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property imagePath (base name: "imagePath")', function() {
      // uncomment below and update the code to test the property imagePath
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property usage (base name: "usage")', function() {
      // uncomment below and update the code to test the property usage
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property sktDate (base name: "sktDate")', function() {
      // uncomment below and update the code to test the property sktDate
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property typeDescription (base name: "typeDescription")', function() {
      // uncomment below and update the code to test the property typeDescription
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property usageInfo (base name: "usageInfo")', function() {
      // uncomment below and update the code to test the property usageInfo
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property usagePeople (base name: "usagePeople")', function() {
      // uncomment below and update the code to test the property usagePeople
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property endTime (base name: "endTime")', function() {
      // uncomment below and update the code to test the property endTime
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

    it('should have the property pharmacy (base name: "pharmacy")', function() {
      // uncomment below and update the code to test the property pharmacy
      //var instance = new KolayAsistanMobileApi.MedicineDTO();
      //expect(instance).to.be();
    });

  });

}));
