/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: v1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMobileApi);
  }
}(this, function(expect, KolayAsistanMobileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMobileApi.UserUpdateDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserUpdateDTO', function() {
    it('should create an instance of UserUpdateDTO', function() {
      // uncomment below and update the code to test UserUpdateDTO
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be.a(KolayAsistanMobileApi.UserUpdateDTO);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be();
    });

    it('should have the property surname (base name: "surname")', function() {
      // uncomment below and update the code to test the property surname
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be();
    });

    it('should have the property identityNo (base name: "identityNo")', function() {
      // uncomment below and update the code to test the property identityNo
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be();
    });

    it('should have the property birthDay (base name: "birthDay")', function() {
      // uncomment below and update the code to test the property birthDay
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be();
    });

    it('should have the property mobilePhone (base name: "mobilePhone")', function() {
      // uncomment below and update the code to test the property mobilePhone
      //var instance = new KolayAsistanMobileApi.UserUpdateDTO();
      //expect(instance).to.be();
    });

  });

}));
