/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 25.04.2023
 *
 * The version of the OpenAPI document: v4.0.0.3
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMobileApi);
  }
}(this, function(expect, KolayAsistanMobileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMobileApi.BatchJobsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BatchJobsApi', function() {
    describe('batchJobControllerCabinetUpdate', function() {
      it('should call batchJobControllerCabinetUpdate successfully', function(done) {
        //uncomment below and update the code to test batchJobControllerCabinetUpdate
        //instance.batchJobControllerCabinetUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchJobControllerCreate', function() {
      it('should call batchJobControllerCreate successfully', function(done) {
        //uncomment below and update the code to test batchJobControllerCreate
        //instance.batchJobControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchJobControllerDelete', function() {
      it('should call batchJobControllerDelete successfully', function(done) {
        //uncomment below and update the code to test batchJobControllerDelete
        //instance.batchJobControllerDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchJobControllerFindAll', function() {
      it('should call batchJobControllerFindAll successfully', function(done) {
        //uncomment below and update the code to test batchJobControllerFindAll
        //instance.batchJobControllerFindAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchJobControllerFindAllByUserId', function() {
      it('should call batchJobControllerFindAllByUserId successfully', function(done) {
        //uncomment below and update the code to test batchJobControllerFindAllByUserId
        //instance.batchJobControllerFindAllByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchJobControllerFindById', function() {
      it('should call batchJobControllerFindById successfully', function(done) {
        //uncomment below and update the code to test batchJobControllerFindById
        //instance.batchJobControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchJobControllerUpdate', function() {
      it('should call batchJobControllerUpdate successfully', function(done) {
        //uncomment below and update the code to test batchJobControllerUpdate
        //instance.batchJobControllerUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
