/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: v1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMobileApi);
  }
}(this, function(expect, KolayAsistanMobileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMobileApi.BloodGlucoseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BloodGlucoseApi', function() {
    describe('bloodGlucoseControllerCreate', function() {
      it('should call bloodGlucoseControllerCreate successfully', function(done) {
        //uncomment below and update the code to test bloodGlucoseControllerCreate
        //instance.bloodGlucoseControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bloodGlucoseControllerDelete', function() {
      it('should call bloodGlucoseControllerDelete successfully', function(done) {
        //uncomment below and update the code to test bloodGlucoseControllerDelete
        //instance.bloodGlucoseControllerDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bloodGlucoseControllerFindUserAllItems', function() {
      it('should call bloodGlucoseControllerFindUserAllItems successfully', function(done) {
        //uncomment below and update the code to test bloodGlucoseControllerFindUserAllItems
        //instance.bloodGlucoseControllerFindUserAllItems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bloodGlucoseControllerFindUserItem', function() {
      it('should call bloodGlucoseControllerFindUserItem successfully', function(done) {
        //uncomment below and update the code to test bloodGlucoseControllerFindUserItem
        //instance.bloodGlucoseControllerFindUserItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bloodGlucoseControllerUpdate', function() {
      it('should call bloodGlucoseControllerUpdate successfully', function(done) {
        //uncomment below and update the code to test bloodGlucoseControllerUpdate
        //instance.bloodGlucoseControllerUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
