/**
 * Kolay Asistan Mobile API
 * Kolay Asistan mobile application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: v1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMobileApi);
  }
}(this, function(expect, KolayAsistanMobileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMobileApi.UserApprovalsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserApprovalsApi', function() {
    describe('approvalControllerCreate', function() {
      it('should call approvalControllerCreate successfully', function(done) {
        //uncomment below and update the code to test approvalControllerCreate
        //instance.approvalControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('approvalControllerDelete', function() {
      it('should call approvalControllerDelete successfully', function(done) {
        //uncomment below and update the code to test approvalControllerDelete
        //instance.approvalControllerDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('approvalControllerFindUserAllItems', function() {
      it('should call approvalControllerFindUserAllItems successfully', function(done) {
        //uncomment below and update the code to test approvalControllerFindUserAllItems
        //instance.approvalControllerFindUserAllItems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('approvalControllerFindUserItem', function() {
      it('should call approvalControllerFindUserItem successfully', function(done) {
        //uncomment below and update the code to test approvalControllerFindUserItem
        //instance.approvalControllerFindUserItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('approvalControllerUpdate', function() {
      it('should call approvalControllerUpdate successfully', function(done) {
        //uncomment below and update the code to test approvalControllerUpdate
        //instance.approvalControllerUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
